[deps]
PolySeries = "6f3fcde8-8165-4326-91a7-f7698485e8a3"
TrackPad = "e7bec244-bd43-46ed-8fec-7dc091d24617"

[sources]
PolySeries = {url = "https://github.com/MSU-Beam-Dynamics/TPSA.jl.git"}
TrackPad = {path = "../../.."}

[compat]
PolySeries = "0.1"
TrackPad = "0.1"
julia = "1.10"
